### ISSUE TITLE
Update LabTestGroup enum

### ISSUE THREAD

**Issue by tahiraniazi** [seekme94/openmrs-module-commonlabtest#2]
Please add the following to LabTestGroup enum in LabTestType.java class
- OPHTHALMOLOGY
- SEROLOGY
- CARDIOLOGY

**Comment by SHUJAAT-DEV** [comment]
**Resolved**! I have added  LabTestGroup enums.

**Comment by seekme94** [comment]
Closing this one, assuming it is tested.
