### ISSUE TITLE
Void Test Result (bulk operation on test attributes)

### ISSUE THREAD

**Issue by tahiraniazi** [seekme94/openmrs-module-commonlabtest#3]
Please add a method in api to void the test result (all attributes at once), also change the status of the PROCESSED sample to COLLECTED and leave the rest of the samples as it is.

**Comment by seekme94** [comment]
Fixed in commit # [1890e88](https://github.com/seekme94/openmrs-module-commonlabtest/commit/1890e88d555be2c39d5066200481ad8dc6ac1cc9) in beta branch
